### ISSUE TITLE
Preview connection to localhost in Docker instances on local not working

### ISSUE THREAD

**Issue by xaviemirmon** [gatsbyjs/wp-gatsby#134]
The current implementation has a mixture of serverside and clientside operations to provide the preview functionality.   This can be problematic when your local browser's network doesn't match that of WordPress's server.

I've run into an issue when running the WordPress instance in a docker container (using Lando), access to localhost is behind the container.  Whereas the localhost from the browser is to my machine's network.   I can fix the WordPress issue by setting the preview URL to host.docker.internal, however, that then breaks all of the JS logic.  

I know this is a super niche problem currently, but I was thinking a hidden URL setting that can be swapped on the WordPress backend activities would be super useful.

**Comment by TylerBarnes** [comment]
You can actually set a different preview URL for server and client by adding a comma separated list (I believe it's server first client second). We're planning on reworking the Gatsby Preview API soon so that all of the preview loading logic is on the Gatsby side which will make this a non-issue. For now a comma should work :)
