### ISSUE TITLE
Comments trigger builds

### ISSUE THREAD

**Issue by moonmeister** [gatsbyjs/wp-gatsby#144]
It'd be nice if Publishing/deleting/editing comments optionally triggered builds. 

Currently I have to ship extra code to fetch comments on the client side. If WP Gatsby triggered a build on CUD operations I could do so on the server and have that comment published really fast which cloud builds. 

One clarification, if a comment is created but held for moderation it shouldn't trigger a build cause it's not "published/public".

**Comment by jacksellwood** [comment]
Hey Alex! What's new?
I chatted with the team about this one, and we're not ready to commit to supporting WP comments in the Gatsby build process. We think the best approach for comments is to render them client side because otherwise build times will get longer and longer.
If this gets a lot of up votes then we'll reconsider it in the future! Closing for now.
