### ISSUE TITLE
Unable to create custom action monitor

### ISSUE THREAD

**Issue by justlevine** [gatsbyjs/wp-gatsby#174]
[As per the docs](https://github.com/gatsbyjs/wp-gatsby/blob/master/docs/action-monitor.md#functional), a custom action monitor should be created as such:

```php
function some_callback( $object ) {
  $monitor = new \WPGatsby\ActionMonitor\Monitors\ActionMonitor();
  $monitor->log_action( $args );
}
```

However, [`Monitors\ActionMonitor`](https://github.com/gatsbyjs/wp-gatsby/blob/master/src/ActionMonitor/Monitors/ActionMonitor.php) [requires ](https://github.com/gatsbyjs/wp-gatsby/blob/master/src/ActionMonitor/Monitors/Monitor.php#L29) an instance of [`WPGatsby\ActionMonitor`](https://github.com/gatsbyjs/wp-gatsby/blob/master/src/ActionMonitor/ActionMonitor.php) and instantiating it without one causes a fatal error. But as far as I can tell, there's no way to get the [existing instance](https://github.com/gatsbyjs/wp-gatsby/blob/08ab1214cf4b5596513063023017b0c3922ca5b8/wp-gatsby.php#L198).

Regardless, the docs need to be updated. [But it's also possible that at some point that WPGatsby stopped supporting custom action monitors,](https://wp-graphql.slack.com/archives/CJUBND25R/p1622672683167100?thread_ts=1622667160.160500&cid=CJUBND25R) and a pr is needed to reimplement the functionality.

---
For reference: [This is where the built-in action monitors are instantiated.](https://github.com/gatsbyjs/wp-gatsby/blob/4e54f260b83d1474d4eea53f8e021098776dfce7/src/ActionMonitor/ActionMonitor.php#L334). The action/filter gives you access to the array of _instantiated_ monitors, but no access to `$this` to instantiate your own.

**Comment by justlevine** [comment]
_If_ a code change is needed here are a few approaches suggested in the slack:

1. Pass `$this` to [`apply_filters( 'gatsby_action_monitors' )`](https://github.com/gatsbyjs/wp-gatsby/blob/master/src/ActionMonitor/ActionMonitor.php#L369) (h/t @alevgal )

2. Make the instance of `WPGatsby/ActionMonitor` publicly available. We can convert it to a singleton (h/t @alevgal ) or even just [save the instance created in wp-gatsby.php to a static var](https://github.com/gatsbyjs/wp-gatsby/blob/master/wp-gatsby.php#L173).

3. Drop the dependency from [`WPGatsby/ActionMonitors/Monitors/Monitor`](https://github.com/gatsbyjs/wp-gatsby/blob/master/src/ActionMonitor/Monitors/Monitor.php). This could be done by [replacing the `$this->action_monitor` calls at the end of `log_action()`](https://github.com/gatsbyjs/wp-gatsby/blob/master/src/ActionMonitor/Monitors/Monitor.php#L333) with a `do_action`, and then hooking them to [run from `WPGatsby\ActionMonitor`'s constructor](https://github.com/gatsbyjs/wp-gatsby/blob/master/src/ActionMonitor/ActionMonitor.php#L52).

**Comment by alevgal** [comment]
Hi, 
My goal is to track the ACF options pages updates. So the easy solution is to add this option to [AcfMonitor](https://github.com/gatsbyjs/wp-gatsby/blob/08ab1214cf4b5596513063023017b0c3922ca5b8/src/ActionMonitor/Monitors/AcfMonitor.php) 

`add_action(
			'acf/save_post',
			function( $id ) {
				if( 'options' === $id ) {
					$page = isset( $_GET['page'] ) ? $_GET['page'] : 'Options page';
					$this->trigger_schema_diff(
						[
							'title' => $page . ' has been updated',
						]
					);
				}
			}
		);`

But digging in to the codeю But when I went into the code to find a solution, I have found [gatsby_action_monitors filter](https://github.com/gatsbyjs/wp-gatsby/blob/08ab1214cf4b5596513063023017b0c3922ca5b8/src/ActionMonitor/ActionMonitor.php#L369), But it doesn't work as the Monitor class [requires ActionMonitor instance as argument](https://github.com/gatsbyjs/wp-gatsby/blob/08ab1214cf4b5596513063023017b0c3922ca5b8/src/ActionMonitor/Monitors/Monitor.php#L29).
So the solution I have tested - 
Add $this as a second argument to  [gatsby_action_monitors filter](https://github.com/gatsbyjs/wp-gatsby/blob/08ab1214cf4b5596513063023017b0c3922ca5b8/src/ActionMonitor/ActionMonitor.php#L369)
`		$this->action_monitors = apply_filters( 'gatsby_action_monitors', $action_monitors, $this );`

Create new monitor class
```
use WPGatsby\ActionMonitor\Monitors\Monitor;

class AcfOptionsMonitor extends Monitor {
	public function init() {
		add_action(
			'acf/save_post',
			function( $id ) {
				if( 'options' === $id ) {
					$page = isset( $_GET['page'] ) ? $_GET['page'] : 'Options page';
					$this->trigger_schema_diff(
						[
							'title' => $page . ' has been updated',
						]
					);
				}
			}
		);
	}
}
```

Add new monitor with filter

```
 add_filter('gatsby_action_monitors', function( $monitors, $action_monitor ) {
        	$acfOptionsMonitor = new AcfOptionsMonitor( $action_monitor );
        	$acfOptionsMonitor->init();
        	$monitors['AcfOptionsMonitor'] = $acfOptionsMonitor;
        	return $monitors;
        }, 10, 2);
```

The only thing - I have a couple option pages, But all updates are added to one action monitor record [because of this check ](https://github.com/gatsbyjs/wp-gatsby/blob/08ab1214cf4b5596513063023017b0c3922ca5b8/src/ActionMonitor/Monitors/Monitor.php#L236-L260)
So may be I should use log_action function instead of trigger_schema_diff? But what params should I pass?

**Comment by justlevine** [comment]
> The only thing - I have a couple option pages, But all updates are added to one action monitor record because of this check
So may be I should use log_action function instead of trigger_schema_diff? But what params should I pass?

The params for the `log_action()` are basically the same as `trigger_schema_diff`, except you manually set `$args['action_type']` to `'CREATE'`, `'UPDATE'`, or `'DELETE'`, and assumingly the [docs example](https://github.com/gatsbyjs/wp-gatsby/blob/master/docs/action-monitor.md#functional) still applies. For what you're describing, use `UPDATE`.

PS: for the meaningful ids/titles from the Options Page, you can use `get_current_screen()` ([see this thread](https://support.advancedcustomfields.com/forums/topic/acfsave_post-for-specific-options-page/)).

**Comment by alevgal** [comment]
Will there be a solution to this problem?
