### ISSUE TITLE
Action Monitor should store bulk events

### ISSUE THREAD

**Issue by jasonbahl** [gatsbyjs/wp-gatsby#40]
If a term is updated, we need to tell Gatsby that all posts in that term should have an update event. 

For example: 

- Term A has 25 posts associated with it
- Term A is deleted
- all 25 posts need an update event

This could look something like: 

```
[
  'actionType' => 'BULK_DELETE',
  'referencedNodeIds' => [ 1, 2, 3, ... ]
]
```

**Comment by TylerBarnes** [comment]
2 things to note:

1. if WPGraphQL or the source plugin get a backreferences api, this wont be as necessary since updating nodes with stale connections wont be necessary. Bulk updates will still be useful for when folks use the WP admin bulk update feature though
2. we need to think about pagination for this. Do we just create a new action for each page of referenced node id's?

**Comment by TylerBarnes** [comment]
I'm moving all current feature request issues to our internal backlog to cleanup GH issues a bit. If anyone feels strongly about this feature please open a request on our new request tracker at https://portal.gatsbyjs.com/gatsby-cloud (or upvote/comment if someone already made one)

Thanks!
