### ISSUE TITLE
Opt in to tracking post types instead of opting out

### ISSUE THREAD

**Issue by TylerBarnes** [gatsbyjs/wp-gatsby#6]
Right now WPGatsby is tracking actions for all post types except for some certain types we've opted out of manually. We need to flip this so it's opt-in instead.

We should automatically opt-in any post type which is set to `show_in_graphql` and has a field on the root query to get a single node of the post type by.
Beyond that there should be a filter which allows folks to choose which types should be tracked.

**Comment by TylerBarnes** [comment]
This change is needed because plugins like "Simple History" may be problematic to automatically track since they're already tracking all user actions. That means we'll be double tracking everything that they're tracking.

**Comment by jasonbahl** [comment]
@TylerBarnes I think this needs to go one step further and the post type should opt-in to something like `show_in_gatsby`. And WPGatsby could even offer a Settings page UI for checking/unchecking post types / Taxonomies to show in Gatsby.

Case in point, I created a quick GraphQL Request logger plugin to log GraphQL requests and help troubleshoot when requests return 503s. 

Anyway, by registering a post type to store GraphQL logs in, and registering it to "show_in_graphql" (because I want to use GraphQL to see the logs), it was causing infinite loops with Gatsby Cloud. . .content in WordPress would change, which would log an action monitor action, which would send a preview webhook to Gatsby Cloud, which would callback to WordPress with a GraphQL Query to get preview data, which would log the GraphQL request, which would log an action monitor action which would send a preview webhook to Gatsby Cloud, which would. . .infinite loop. 

I think it's dangerous to assume _every_ post type that is set to show_in_graphql should also _show_ in Gatsby.

_Possibly_ we could default to `get_post_types( [ 'public' => true, 'show_in_graphql' => true ]);`. 

`public => true` indicates it's a post type that's intended to have a public facing URL, and I think most often this will be the type of post type that matters to Gatsby. 

I do think though that a more explicit `show_in_gatsby => true/false` option for post types and taxonomies would be ideal.

**Comment by TylerBarnes** [comment]
I think a `show_in_gatsby` would introduce too much friction, but `[ 'public' => true, 'show_in_graphql' => true ]` is 100% right because Gatsby can only consume public data anyway. What we could add is a `disclude_from_gatsby_updates` or something like that so you can easily have a post type opt-out. This is only for tracking data updates, not for what data Gatsby will fetch, so if a post type is public and shown in GraphQL, Gatsby will fetch it. `show_in_gatsby` would be confusing because it would still show in Gatsby but the data would never update until you set that to true.

**Comment by jasonbahl** [comment]
closed by #74
