### ISSUE TITLE
Uploading/editing images shouldn't trigger webhooks

### ISSUE THREAD

**Issue by jasonbahl** [gatsbyjs/wp-gatsby#81]
With the release of v0.8.0, uploading images now triggers an action, but this feels like a mistake. When working on publishing a new post, I uploaded a few images, then clicked publish, and I had to wait for the builds triggered by the image uploads to complete before my published post build would run. 

I think we should revert the behavior of triggering an action for image uploads as publishing a post that contains images will fetch the needed images.

**Comment by jasonbahl** [comment]
@TylerBarnes this one is tricky. 

Image uploads and updates currently trigger builds which create a queue and then when publishing a post the build for the post must now wait for the builds that were triggered by image uploads/deletes to complete. 

I'm thinking maybe we add a mechanism to still log an action in action_monitor, but ignore triggering the dispatch?

This way we can still store an action that indicates Image XX was uploaded/edited, but that action will only be received by Gatsby when _another_ action (such as publish post) triggers a webhook. 

So my workflow as a user would be: 

- Upload image (this logs an action, but doesn't send a webhook)
- Edit the image (this logs an action, but doesn't send a webhook)
- Publish my post (this logs an action, AND sends a webhook)

Gatsby build is triggered, it fetches actions, finds the image and the post in the actions and runs the builds. 

----

The tradeoff here, though, is that editing an image, but not editing a post or doing any other action that triggers a build would mean the images used within a post, that have been edited, wouldn't be picked up by Gatsby until another action that triggers a build were run. 🤔

**Comment by jasonbahl** [comment]
Possibly for now we ignore Image Upload actions altogether, but still track image edits? 🤔 

Maybe we can track image edits only if the image date is older than the most recently modified post? 

If the date of the image is newer than the most recently modified post, then we can be pretty sure that the image isn't being used on a post and can log an action but not trigger a webhook? 🤔

**Comment by TylerBarnes** [comment]
Nah, we need to save an action for every change to a media item node wether it's a new upload or an edit. It worked like this before too so it's not a regression. But I definitely agree we don't need to dispatch webhooks when media items are uploaded/edited. The only place this is tricky is with previews. Previews are only pulling the one node you're previewing instead of all content updates. Which means you might not be able to preview an image edit if we do this. So this will require more thought and trying things out.

**Comment by TylerBarnes** [comment]
We don't need to compare dates because a content build will always pull all actions into Gatsby that it hasn't yet processed. So the presence of the actions is enough, then when someone updates a post it'll pull in any media item updates. Since we're only pulling images that are connected to a post somewhere this should work fine 👍

**Comment by TylerBarnes** [comment]
This is published in WPGatsby 0.9.0. Thanks @jasonbahl !
